services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: chatter
      POSTGRES_PASSWORD: chatter
      POSTGRES_DB: chatter
    ports:
      - "5432:5432"
    volumes:
      - chatter_pg_data:/var/lib/postgresql/data

volumes:
  chatter_pg_data:
